import {
  builtInProviderIds,
  providerLayerExtensions,
  type BuiltInProviderId,
} from '../../shared/providers.js';
import { providerLayer, type SourceLayer } from './classify.js';

const providerDependencies = (provider: BuiltInProviderId): readonly SourceLayer[] => [
  'contracts',
  'discovery-platform',
  providerLayer(provider),
  'providers-shared',
  ...(providerLayerExtensions[provider] ?? []),
];

const allowedDependencies: Readonly<Partial<Record<SourceLayer, readonly SourceLayer[]>>> = {
  contracts: ['contracts'],
  'configuration-core': ['configuration-core', 'contracts', 'definition-foundation'],
  'definition-foundation': ['contracts', 'definition-foundation'],
  'definition-profile': ['contracts', 'definition-foundation'],
  'definition-core': [
    'contracts',
    'definition-core',
    'definition-foundation',
    'definition-profile',
  ],
  'discovery-platform': ['discovery-platform'],
  'platform-discovery': ['discovery-platform', 'platform-discovery'],
  'discovery-runner': ['contracts', 'definition-foundation', 'definition-core'],
  'discovery-root': [
    'contracts',
    'discovery-platform',
    'platform-discovery',
    'discovery-runner',
    'providers-composition',
  ],
  'providers-shared': ['contracts', 'discovery-platform', 'providers-shared'],
  'providers-composition': [
    'contracts',
    'discovery-platform',
    'execution-configuration',
    'protocol-acp',
    ...builtInProviderIds.map(providerLayer),
  ],
  'application-active-state': [
    'application-active-state',
    'contracts',
    'definition-core',
    'execution-process',
    'execution-process-port',
  ],
  'application-configuration': ['application-configuration', 'contracts'],
  'application-faults': [
    'contracts',
    'execution-invocation',
    'execution-output',
    'execution-probe',
  ],
  'application-invocation': [
    'application-active-state',
    'application-configuration',
    'application-faults',
    'application-invocation',
    'application-manager',
    'application-result',
    'contracts',
    'definition-core',
    'execution-invocation',
    'execution-output',
    'execution-result',
  ],
  'application-result': [
    'application-faults',
    'contracts',
    'execution-invocation',
    'execution-output',
    'execution-result',
  ],
  'application-manager': [
    'application-active-state',
    'application-configuration',
    'application-faults',
    'application-invocation',
    'application-manager',
    'application-result',
    'application-session-management',
    'contracts',
    'definition-core',
    'definition-profile',
    'execution-invocation',
    'execution-configuration',
    'execution-output',
    'execution-probe',
    'execution-process',
    'execution-process-port',
    'execution-result',
  ],
  'execution-configuration': [
    'configuration-core',
    'contracts',
    'execution-configuration',
    'execution-output',
    'execution-process',
    'execution-process-port',
    'protocol-driver',
  ],
  'execution-invocation': [
    'contracts',
    'execution-invocation',
    'execution-output',
    'execution-process',
    'execution-process-port',
    'execution-result',
    'execution-security',
    'protocol-driver',
  ],
  'execution-output': ['contracts', 'execution-output', 'execution-security'],
  'execution-result': ['contracts', 'execution-output', 'execution-result', 'execution-security'],
  'execution-security': ['execution-security'],
  'execution-probe': [
    'contracts',
    'definition-foundation',
    'execution-probe',
    'execution-process',
    'execution-process-port',
  ],
  'execution-process': ['contracts'],
  'execution-process-port': ['contracts'],
  'platform-output': [
    'execution-invocation',
    'execution-output',
    'platform-output',
    'platform-process',
  ],
  'platform-probe': [
    'execution-probe',
    'execution-process',
    'execution-process-port',
    'platform-process',
  ],
  'platform-process': ['execution-process', 'execution-process-port', 'platform-process'],
  'protocol-driver': ['configuration-core', 'contracts'],
  'protocol-acp': ['configuration-core', 'contracts', 'protocol-acp', 'protocol-driver'],
  root: [
    'contracts',
    'contracts-session',
    'discovery-root',
    'application-manager',
    'execution-configuration',
    'execution-invocation',
    'execution-probe',
    'platform-output',
    'platform-session-output',
    'platform-session-primitives',
    'platform-security-digest',
    'platform-probe',
    'platform-process',
    'protocol-acp',
    'protocol-acp-session',
    'providers-composition',
  ],
};

export const baseDependenciesFor = (layer: SourceLayer): readonly SourceLayer[] | undefined => {
  const provider = builtInProviderIds.find((candidate) => providerLayer(candidate) === layer);
  return provider === undefined ? allowedDependencies[layer] : providerDependencies(provider);
};
