import type { SourceLayer } from './classify.js';

const allowedDependencies: Readonly<Partial<Record<SourceLayer, readonly SourceLayer[]>>> = {
  'contracts-session': ['contracts', 'contracts-session'],
  'contracts-session-continuation-envelope': ['contracts', 'contracts-session'],
  'session-kernel': [
    'contracts',
    'contracts-session',
    'session-kernel',
    'session-kernel-effects',
    'session-kernel-public-command',
  ],
  'session-kernel-effects': [
    'contracts',
    'contracts-session',
    'session-kernel',
    'session-kernel-effects',
  ],
  'session-kernel-public-command': ['contracts', 'contracts-session', 'session-kernel'],
  'protocol-session': ['configuration-core', 'contracts', 'protocol-session'],
  'session-runtime': [
    'contracts-session',
    'session-kernel',
    'session-kernel-effects',
    'session-kernel-public-command',
    'session-runtime',
    'session-runtime-dispatch',
    'session-runtime-identity-port',
    'session-runtime-outcome-port',
  ],
  'session-runtime-dispatch': ['contracts-session', 'session-kernel-public-command'],
  'session-runtime-identity-port': ['contracts', 'contracts-session'],
  'session-runtime-outcome-port': ['contracts-session', 'session-kernel-effects'],
  'execution-security-digest-port': ['contracts'],
  'execution-session-output-port': ['contracts', 'contracts-session'],
  'session-interpreter': [
    'contracts',
    'contracts-session',
    'contracts-session-continuation-envelope',
    'execution-session-output-port',
    'execution-process-port',
    'execution-security-digest-port',
    'protocol-session',
    'session-kernel-effects',
    'session-runtime-identity-port',
    'session-runtime-outcome-port',
  ],
  'application-session-boundary': [
    'application-session-boundary',
    'contracts',
    'contracts-session',
    'contracts-session-continuation-envelope',
    'definition-foundation',
    'execution-security-digest-port',
  ],
  'application-session-policy': [
    'application-session-policy',
    'contracts',
    'contracts-session',
    'definition-core',
    'definition-foundation',
    'definition-profile',
  ],
  'application-session-management': [
    'application-session-boundary',
    'application-session-management',
    'application-session-policy',
    'contracts',
    'contracts-session',
    'session-runtime-dispatch',
  ],
  'application-session-handles': [
    'application-session-handles',
    'contracts',
    'contracts-session',
    'session-kernel-public-command',
    'session-runtime-dispatch',
  ],
  'protocol-acp-session': [
    'configuration-core',
    'contracts',
    'protocol-acp',
    'protocol-acp-session',
    'protocol-session',
  ],
  'platform-session-output': [
    'execution-session-output-port',
    'platform-output',
    'platform-process',
  ],
  'platform-session-primitives': ['session-runtime-identity-port'],
  'platform-security-digest': ['execution-security-digest-port'],
};

export const sessionDependenciesFor = (layer: SourceLayer): readonly SourceLayer[] | undefined =>
  allowedDependencies[layer];
